spring:
  datasource:
    url: jdbc:postgresql://localhost:9999/db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

app:
  testcontainers-postgres:
    enabled: false
